language: node_js
node_js: '6'
services: mongodb
before_script: sleep 15
cache:
  directories:
    - node_modules
    - client/node_modules
script:
  - npm run lint
  - npm run flow
  - npm run test
  - npm run test:client
  - npm run docs
